### ISSUE TITLE
setup.py install raises "invalid token" error

### ISSUE THREAD

**Issue by msarm** [hootnot/oanda-trading-environment#10]
Getting below error while installing...  working with Python 3.7.5
```
(venv) C:\Users\user\source\repos\oanda\oanda-trading-environment>python setup.py install
  File "setup.py", line 17
    "etc/OANDA": 0700,
                    ^
SyntaxError: invalid token
```

**Comment by hootnot** [comment]
This is a Python 3 issue. Python 3 uses 0o for octal representation. Changing these to 0o700 should fix it. I'll have a look at it.

**Comment by msarm** [comment]
> This is a Python 3 issue. Python 3 uses 0o for octal representation. Changing these to 0o700 should fix it. I'll have a look at it.

Issue resolved!
